apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  finalizers:
    - tempo.grafana.com/finalizer
  labels:
    platform.opendatahub.io/part-of: monitoring
  name: data-science-tempomonolithic
  namespace: redhat-ods-monitoring
spec:
  extraConfig:
    tempo:
      compactor:
        compaction:
          block_retention: 2160h0m0s
  multitenancy:
    authentication:
      - tenantId: redhat-ods-monitoring
        tenantName: redhat-ods-monitoring
    enabled: true
    mode: openshift
  resources:
    limits:
      cpu: "1"
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  storage:
    traces:
      backend: pv
  timeout: 0s
