apiVersion: v1
data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            resources:
              requests:
                cpu: 500m
                memory: 2Gi
              limits:
                memory: 8Gi
  horizontalPodAutoscaler: |-
    spec:
      minReplicas: 2
      maxReplicas: 4
  service: |
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: "data-science-gateway-service-tls"
    spec:
      type: ClusterIP
kind: ConfigMap
metadata:
  labels:
    platform.opendatahub.io/part-of: gatewayconfig
  name: data-science-gateway-config
  namespace: openshift-ingress
