apiVersion: kuadrant.io/v1alpha1
kind: TokenRateLimitPolicy
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: maas-controller
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
    app.opendatahub.io/modelsasservice: "true"
    maas.opendatahub.io/tenant-name: default-tenant
    maas.opendatahub.io/tenant-namespace: models-as-a-service
  name: gateway-default-deny
  namespace: openshift-ingress
spec:
  defaults:
    limits:
      deny-all-by-default:
        counters:
          - expression: auth.identity.userid
        rates:
          - limit: 0
            window: 1m
        when:
          - predicate: '!request.path.startsWith("/maas-api") && !request.path.startsWith("/v1/models")'
    strategy: atomic
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
