apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/managed-by: maas-controller
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
    app.opendatahub.io/modelsasservice: "true"
    maas.opendatahub.io/tenant-name: default-tenant
    maas.opendatahub.io/tenant-namespace: models-as-a-service
  name: gateway-default-auth
  namespace: openshift-ingress
spec:
  defaults:
    rules:
      authentication: {}
      authorization:
        deny-unconfigured-models:
          metrics: false
          patternMatching:
            patterns:
              - operator: eq
                selector: context.request.http.method
                value: __deny_unconfigured_models__
          priority: 0
    strategy: atomic
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
