apiVersion: extensions.kuadrant.io/v1alpha1
kind: TelemetryPolicy
metadata:
  finalizers:
    - kuadrant.io/extensions
  labels:
    app.kubernetes.io/part-of: maas-observability
    maas.opendatahub.io/tenant-name: default-tenant
    maas.opendatahub.io/tenant-namespace: models-as-a-service
  name: maas-telemetry
  namespace: openshift-ingress
spec:
  metrics:
    default:
      labels:
        cost_center: auth.identity.subscription_info.costCenter
        model: responseBodyJSON("/model")
        organization_id: auth.identity.subscription_info.organizationId
        subscription: auth.identity.selected_subscription
        user: auth.identity.userid
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
