apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: maas-default-gateway-request-rate-limits
  namespace: openshift-ingress
spec:
  limits:
    team-alpha-tier-requests:
      counters:
        - expression: auth.identity.userid
      rates:
        - limit: 5
          window: 1m
      when:
        - predicate: auth.identity.tier == "team-alpha-tier" && !request.path.endsWith("/v1/models")
    team-bravo-tier-requests:
      counters:
        - expression: auth.identity.userid
      rates:
        - limit: 30
          window: 1m
      when:
        - predicate: auth.identity.tier == "team-bravo-tier" && !request.path.endsWith("/v1/models")
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: maas-default-gateway
