apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSModelRef
metadata:
  annotations:
    openshift.io/display-name: qwen2.5-0.5b-instruct-maas
  finalizers:
    - maas.opendatahub.io/model-cleanup
  name: qwen25-05b-instruct-maas
  namespace: vllm-project
spec:
  modelRef:
    kind: LLMInferenceService
    name: qwen25-05b-instruct-maas
