apiVersion: maas.opendatahub.io/v1alpha1
kind: MaaSSubscription
metadata:
  annotations:
    openshift.io/display-name: team-bravo
  finalizers:
    - maas.opendatahub.io/subscription-cleanup
  name: team-bravo
  namespace: models-as-a-service
spec:
  modelRefs:
    - name: llama-32-1b-instruct-llmd-2
      namespace: vllm-project
      tokenRateLimits:
        - limit: 1000
          window: 1m
    - name: qwen25-05b-instruct-llmd
      namespace: vllm-project
      tokenRateLimits:
        - limit: 1000
          window: 1m
    - name: llama-32-1b-instruct-maas
      namespace: vllm-project
      tokenRateLimits:
        - limit: 10000
          window: 1m
    - name: qwen25-05b-instruct-maas
      namespace: vllm-project
      tokenRateLimits:
        - limit: 10000
          window: 1m
  owner:
    groups:
      - name: team-bravo
  priority: 1
  tokenMetadata:
    costCenter: CC-00002
    organizationId: ORG-00001
