apiVersion: v1
data:
  tiers: |
    # Free tier
    - name: free
      displayName: Free Tier
      level: 0
      groups:
        - system:authenticated
    # Premium
    - name: premium
      displayName: Premium Tier
      level: 1
      groups:
        - premium-group
    # Enterprise
    - name: enterprise
      displayName: Enterprise Tier
      level: 2
      groups:
        - enterprise-group
    # Team Alpha
    - name: team-alpha-tier
      displayName: Team Alpha
      level: 3
      groups:
        - team-alpha
    # Team Bravo
    - name: team-bravo-tier
      displayName: Team Bravo
      level: 4
      groups:
        - team-bravo
kind: ConfigMap
metadata:
  labels:
    app: maas-api
    app.kubernetes.io/component: api
    app.kubernetes.io/name: maas-api
    app.kubernetes.io/part-of: models-as-a-service
    app.opendatahub.io/modelsasservice: "true"
    component: tier-mapping
    platform.opendatahub.io/part-of: modelsasservice
  name: tier-to-group-mapping
  namespace: redhat-ods-applications
