---
apiVersion: v1
kind: Secret
metadata:
  name: get-a-username-secret
  namespace: guides
type: Opaque
stringData:
  LAB_REDIS_PASS: "redis"
  LAB_USER_ACCESS_TOKEN: "Workshop"
  LAB_USER_PASS: "Workshop"
  LAB_ADMIN_PASS: "Workshop"
