# Required: change all default secrets
postgresql:
  auth:
    password: "tBwJDvtAMbTzzg9T7Ki935RzhDHE9ZRHiv/SmhvWdLI="    # openssl rand -base64 32

litellm:
  auth:
    masterKey: "sk-very-secure-password"     # Must start with sk-
    uiUsername: "admin"
    uiPassword: "admin"

backend:
  auth:
    jwtSecret: "tBwJDvtAMbTzzg9T7Ki935RzhDHE9ZRHiv/SmhvWdLI="        # openssl rand -base64 32
    adminApiKeys: "tBwJDvtAMbTzzg9T7Ki935RzhDHE9ZRHiv/SmhvWdLI="     # openssl rand -base64 32
    litellmApiKey: "sk-very-secure-password" # Must match litellm.auth.masterKey