---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../../bases/grafana/
- ./../../bases/kyverno/
- ./policies/
# - ./vpa/


patches:
- path: ./patches/kyverno/psm.yaml
# - target:
#     group: policy
#     version: v1beta1
#     kind: PodDisruptionBudget
#   patch: |-
#     [
#       {
#         "op": "replace",
#         "path": "/apiVersion",
#         "value": "policy/v1"
#       }
#     ]