resources:
  - acm-right-sizing-namespace.yaml
  - admin-api--network-analysis.yaml
  - admin-cluster-health.yaml
  - admin-ocp-cluster-overview.yaml
  - admin-vpa-optimization--health.yaml
  - rhoai-gpu-utilization--consumption.yaml
  - rhoai-inference-endpoint-monitoring.yaml
  - rhoai-vllm--gpu-master-dashboard.yaml
  - rhoai-vllm-performance-monitor.yaml
  - vllm-advanced-performance-dashboard.yaml
