resources:
  - acm-right-sizing-namespace.yaml
  - admin-api--network-analysis.yaml
  - admin-cluster-health.yaml
  - admin-vpa-optimization--health.yaml
  - ai-maas-admin--analyst---usage--rate-limits.yaml
  - ai-platform-admin---model-performance.yaml
  - ai-platform-admin---overview.yaml
  - maas-stakeholder-summary.yaml
  - platform-gitops--multi-tenancy-health.yaml
