---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml

namespace: my-demo-app

images:
- name: nginx
  newName: registry.disconnected.local:5000/my-project/nginx
  newTag: latest
