# This patch targets the LokiStack CR
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: instance
spec:
  storage:
    secret:
      # **This is the field we are overriding for UAT**
      # The base might be 'logging-loki-s3-config-base', and this changes it to a UAT-specific secret.
      name: logging-loki-s3-config-uat